### ISSUE TITLE
Many2Many relationship with shadow keys after adding state is Unchanged

### ISSUE THREAD

**Issue by synercoder** [aspnet/EntityFrameworkCore#10388]
When creating a many to many class with only navigation properties (with the key properties as shadow properties), the context doesn't set the entity state to Added when calling the `DbSet<>.Add(...)` method.

After adding the relation object, the entry state is `EntityState.Unchanged`

### In short
Model:

    public class FooBar
    {
        public Foo Foo { get; set; }
        public Bar Bar { get; set; }
    }

OnModelCreating:

    modelBuilder.Entity<FooBar>().Property(typeof(Guid), "Foo_Id");
    modelBuilder.Entity<FooBar>().HasOne(x => x.Foo).WithMany(x => x.FooBars).HasForeignKey("Foo_Id");
    modelBuilder.Entity<FooBar>().Property(typeof(Guid), "Bar_Id");
    modelBuilder.Entity<FooBar>().HasOne(x => x.Bar).WithMany(x => x.FooBars).HasForeignKey("Bar_Id");
    modelBuilder.Entity<FooBar>().HasKey("Foo_Id", "Bar_Id");

Then calling:

    var entry = context.FooBars.Add(new FooBar() { Foo = foo1, Bar = bar1 });
    //Console.WriteLine(entry.State == EntityState.Unchanged); // True
    context.SaveChanges();

Then nothing is saved...

### Steps to reproduce
I created a Gist with a small project to reproduce the problem: https://gist.github.com/synercoder/ca54951d01b75bf07a06c960405e5ec3

When you run the project the first "round" will not add the relations.

I created a workaround (just set the entity state to added) that does add the relations (second "round").

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro
IDE: Visual Studio 2017 (15.4.4)

**Comment by BladeWise** [comment]
Have you tried adding entities directly to the context?
```c#
context.Add(new FooBar() { Foo = foo1, Bar = bar1 });
```
I have experienced the same issue, and despite the fact that both [DbContext.Add<T>](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.add?view=efcore-2.0) and [DbSet<T>.Add](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbset-1.add?view=efcore-2.0) claim to track related entities, I've found cases where the first works, and the latter fails silently.

**Comment by synercoder** [comment]
@BladeWise I tried it with just `context.Add(...);` and the result was the same. The entity was not added.

**Comment by ajcvickers** [comment]
@BladeWise "I've found cases where the first works, and the latter fails silently" Can you please file an issue for this including the steps needed to reproduce this behavior--seems like a bug.

**Comment by BladeWise** [comment]
@ajcvickers To be fair, it happened with pre-2.0.0 releases, and since then I have yet to work on this. If I happen to be bitten by this again, I'll provide feedback. Anyway, you can confirm that both Add methods should behave the same, right?

**Comment by ajcvickers** [comment]
@BladeWise Yes. The code for DbSet.Add just calls directly into DbContext.Add.

**Comment by AndriySvyryd** [comment]
No longer reproes, probably fixed in bd5003708db99022377af9252ea8c9ae610eedd6

**Comment by synercoder** [comment]
I still get the following output in my console:

```
Recreating database...
Adding foos and bars...
Adding relationships using DbSet<>.Add
Checking relationship count...
OMG OMG OMG!! BUG BUG BUG! FIRE AND BRIMSTONE!
Count is 0 instead of 6.

Recreating database...
Adding foos and bars...
Adding relationships using DbSet<>.Add(...).State = EntityState.Added
Checking relationship count...
Everything is as it should be.

Done...
```

Tested with:     Microsoft.EntityFrameworkCore.SqlServer: 2.1.0-preview3-32116

**Comment by synercoder** [comment]
Also updated my Gist (https://gist.github.com/synercoder/ca54951d01b75bf07a06c960405e5ec3) to use a nuget config linked to the MyGet feeds.

**Comment by synercoder** [comment]
@AndriySvyryd still reproes could you investigate again? As you can see by my output. The first round still errors.

**Comment by synercoder** [comment]
@AndriySvyryd Forgot to say.... And better late than never... Thanks!
