### ISSUE TITLE
Projection collection SQL can be simplified

### ISSUE THREAD

**Issue by SSkovboiSS** [aspnet/EntityFrameworkCore#10846]
```C#
var currentUserInfo = await UnitOfWork.RepoParent
                    .GetAll(p => p.Id == CurrentUserId)
                    .Select(p => new
                    {
                        p.IsVerified,
                        Verifies = p.Verifies.ToList(),
                        Fullname = UserNameUtils.JoinName(p.FirstName, p.MiddleName, p.LastName),
                        FriendsId = p.Friends.Select(f => f.FriendId).ToList()
                    })
                    .SingleOrDefaultAsync();
```

Gets translated into:
```sql
SELECT TOP(2) [p].[Id], [p].[AddressId], [p].[BillingDate], [p].[ChangeSubscriptionDate], [p].[CreateDate], [p].[CreateId], [p].[CreditsBalance], [p].[DidLoginAfterVerify], [p].[DisplayCo
stType], [p].[FirstName], [p].[IsFundraising], [p].[IsVerified], [p].[LastName], [p].[LastOnline], [p].[MiddleName], [p].[ModDate], [p].[ModId], [p].[NumberWWCC], [p].[PaidAmount], [p].[Photo],
 [p].[RankTypeId], [p].[ReferralCode], [p].[ReferrerId], [p].[SecurityCode], [p].[SubscriptionId]
      FROM [Parent] AS [p]
      WHERE [p].[Id] = @__CurrentUserId_0
      ORDER BY [p].[Id]

SELECT [p.Verifies].[Id], [p.Verifies].[Confirmed], [p.Verifies].[CreateDate], [p.Verifies].[CreateId], [p.Verifies].[ModDate], [p.Verifies].[ModId], [p.Verifies].[ParentId], [p.Verifies]
.[Token], [p.Verifies].[VerifierId]
      FROM [Verify] AS [p.Verifies]
      INNER JOIN (
          SELECT TOP(1) [p0].[Id]
          FROM [Parent] AS [p0]
          WHERE [p0].[Id] = @__CurrentUserId_0
          ORDER BY [p0].[Id]
      ) AS [t] ON [p.Verifies].[ParentId] = [t].[Id]
      ORDER BY [t].[Id]

SELECT [f].[FriendId]
      FROM [Friend] AS [f]
      WHERE @_outer_Id = [f].[ParentId]
```

Are there any reason to use inner join when querying Verifies? Also if I add projection to Verifies collection like this: Verifies = `p.Verifies.Select(v => v).ToList()` generated SQL does get optimized:

```
SELECT TOP(2) [p].[IsVerified], [p].[Id], [p].[FirstName], [p].[MiddleName], [p].[LastName]
      FROM [Parent] AS [p]
      WHERE [p].[Id] = @__CurrentUserId_0

SELECT [v].[Id], [v].[Confirmed], [v].[CreateDate], [v].[CreateId], [v].[ModDate], [v].[ModId], [v].[ParentId], [v].[Token], [v].[VerifierId]
      FROM [Verify] AS [v]
      WHERE @_outer_Id = [v].[ParentId]

SELECT [f].[FriendId]
      FROM [Friend] AS [f]
      WHERE @_outer_Id1 = [f].[ParentId]
```

Could be the case that it was fixed in nightly 2.1 builds, but unforunately I didn't have time to give it a try.

## Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SQLServer
Operating system: Windows 10 1703
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
We think this is already fixed in our working code base. If you want to test this, then the feeds for our nightly builds are listed on the repo homepage: https://github.com/aspnet/EntityFrameworkCore

**Comment by SSkovboiSS** [comment]
I tested it using Entity Framework Core 2.1.0-preview2-30070 and wish to share some feedback. Indeed this was partially fixed in latest builds:

```sql
SELECT TOP(2) [p].[IsVerified], [p].[Id], [p].[FirstName], [p].[MiddleName], [p].[LastName]
      FROM [Parent] AS [p]
      WHERE [p].[Id] = @__CurrentUserId_0
      ORDER BY [p].[Id]

SELECT [p.Verifies].[Id], [p.Verifies].[Confirmed], [p.Verifies].[CreateDate], [p.Verifies].[CreateId], [p.Verifies].[ModDate], [p.Verifies].[ModId], [p.Verifies].[ParentId], [p.Verifies].[Token], [p.Verifies].[VerifierId], [t].[Id]
      FROM [Verify] AS [p.Verifies]
      INNER JOIN (
          SELECT TOP(1) [p0].[Id]
          FROM [Parent] AS [p0]
          WHERE [p0].[Id] = @__CurrentUserId_0
          ORDER BY [p0].[Id]
      ) AS [t] ON [p.Verifies].[ParentId] = [t].[Id]
      ORDER BY [t].[Id]

SELECT [t0].[Id], [p.Friends].[FriendId], [p.Friends].[ParentId]
      FROM [Friend] AS [p.Friends]
      INNER JOIN (
          SELECT TOP(1) [p1].[Id]
          FROM [Parent] AS [p1]
          WHERE [p1].[Id] = @__CurrentUserId_0
          ORDER BY [p1].[Id]
      ) AS [t0] ON [p.Friends].[ParentId] = [t0].[Id]
      ORDER BY [t0].[Id]
```

First query got optimized, but those joins are still present. However I think this is already tracked by #2182.

Interestingly, the hack I tried as a workaround is not working anymore.
> if I add projection to Verifies collection like this: Verifies = p.Verifies.Select(v => v).ToList() generated SQL does get optimized
