### ISSUE TITLE
Order of entity mappings matters when dealing with shadow properties

### ISSUE THREAD

**Issue by seroche** [aspnet/EntityFrameworkCore#13300]
Our `User` entity has a One-To-many relationship with another entity called `Profile`. 

You may find the mappings we are using below:
```C#
        builder.Entity<User>(m =>
            {
                m.ToTable("User", "user");
                m.HasKey(x => x.Id);
                m.Property(x => x.Id)
                    .HasColumnName("UserId");
                m.Property("_email")
                    .HasColumnName("Email");
                m.Property(x => x.AdditionalEmail)
                    .HasConversion(ValueConverters.EmailConverter);
              
               << Relationship definition
                m.HasMany<Profile>("_profiles")
                    .WithOne()
                    .HasForeignKey("Email")
                    .HasPrincipalKey("_email");

                m.HasMany<UserRole>("_roles")
                    .WithOne()
                    .HasForeignKey(x => x.Id)
                    .HasPrincipalKey(x => x.Id);

                m.Ignore(x => x.Email);
                m.Ignore(x => x.Profiles);
                m.Ignore(x => x.Roles);
            });

            builder.Entity<Profile>(m =>
            {
                m.ToTable("Profile", "user");
                m.HasKey(x => x.Id);
                m.Property(x => x.Id)
                    .HasColumnName("ProfileId");
                m.Property(x => x.DirectLine)
                    .HasColumnName("PhoneNumber")
                    .HasConversion(ValueConverters.PhoneNumberConverter);
                m.Property(x => x.MobileNumber)
                    .HasConversion(ValueConverters.PhoneNumberConverter);
                m.Property(x => x.FaxNumber)
                    .HasConversion(ValueConverters.PhoneNumberConverter);

                // Shadow properties
                m.Property<string>("Email"); << Used as a FK.
                m.Property<int>("TecTacContactId");
            });
```
If `Profile` related mappings are added **after** those for the `User` entity, EF Core will end up throwing the following exception:
`System.InvalidOperationException: 'The types of the properties specified for the foreign key {'Email'} on entity type 'Profile' do not match the types of the properties in the principal key {'_email'} on entity type 'User'.'`

If `Profile` related mappings are added **before** those for the `User` entity, it works fine...

To me the order should not matter?

Note: If I add a private field called _email and updating the mappings, then order does not matter anymore. It seems to be related to shadow properties?

### Further technical details
EF Core version: 2.1.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by ajcvickers** [comment]
@seroche Please post the User and Profile classes.

**Comment by seroche** [comment]
Here they are. Entity base class just contains a property called Id. For the sake of simplicity I removed all methods from those class to keep them short!

    public class User : Entity<Guid>, IAggregateRoot
    {
        private string _email = string.Empty;
        private readonly List<UserRole> _roles = new List<UserRole>();
        private readonly List<Profile> _profiles = new List<Profile>();

        public Email Email => Email.Create(_email);
        public Email AdditionalEmail { get; set; }
        public string JobTitle { get; set; }

        public IReadOnlyCollection<Role> Roles
            => _roles.Select(x => x.Role).ToReadOnlyCollection();
        public IReadOnlyCollection<Profile> Profiles
            => _profiles.Where(x => x.IsActive).ToReadOnlyCollection();

        protected User() { }
    }

    public class Profile : Entity<Guid>
    {
        public Guid ClientId { get; private set; }
        public PhoneNumber DirectLine { get; private set; }
        public PhoneNumber MobileNumber { get; private set; }
        public PhoneNumber FaxNumber { get; private set; }
        public DateTime CreationDate { get; private set; }
        public bool IsActive { get; private set; }

        protected Profile() { }
    }

**Comment by AndriySvyryd** [comment]
@ajcvickers Did this repro on 2.2?

**Comment by ajcvickers** [comment]
@AndriySvyryd Didn't try--thought it might be a dupe, but figured you would know better. I can try on 2.2 to confirm if you think this is fixed already.

**Comment by AndriySvyryd** [comment]
Yes, should have been fixed by 4cd2a5df871383c8a9ddb9817170f2b0013bf537

**Comment by ajcvickers** [comment]
@AndriySvyryd Still fails in 2.2 with exception below. Passes if Profile is configured first.

```
Microsoft.EntityFrameworkCore.Query.QueryBugsTest.Main

System.InvalidOperationException : The types of the properties specified for the foreign key {'Email'} on entity type 'Profile' do not match the types of the properties in the principal key {'_email'} on entity type 'Userr'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey.AreCompatible(IReadOnlyList`1 principalProperties, IReadOnlyList`1 dependentProperties, EntityType principalEntityType, EntityType dependentEntityType, Boolean shouldThrow) in C:\aspnet\EntityFrameworkCore\src\EFCore\Metadata\Internal\ForeignKey.cs:line 807
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey.AreCompatible(EntityType principalEntityType, EntityType dependentEntityType, MemberInfo navigationToPrincipal, MemberInfo navigationToDependent, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 principalProperties, Nullable`1 unique, Nullable`1 required, Boolean shouldThrow) in C:\aspnet\EntityFrameworkCore\src\EFCore\Metadata\Internal\ForeignKey.cs:line 717
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceCollectionBuilderBase..ctor(InternalRelationshipBuilder builder, ReferenceCollectionBuilderBase oldBuilder, Boolean foreignKeySet, Boolean principalKeySet, Boolean requiredSet) in C:\aspnet\EntityFrameworkCore\src\EFCore\Metadata\Builders\ReferenceCollectionBuilderBase.cs:line 73
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceCollectionBuilder..ctor(InternalRelationshipBuilder builder, ReferenceCollectionBuilder oldBuilder, Boolean foreignKeySet, Boolean principalKeySet, Boolean requiredSet) in C:\aspnet\EntityFrameworkCore\src\EFCore\Metadata\Builders\ReferenceCollectionBuilder.cs:line 46
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceCollectionBuilder`2..ctor(InternalRelationshipBuilder builder, ReferenceCollectionBuilder oldBuilder, Boolean foreignKeySet, Boolean principalKeySet, Boolean requiredSet) in C:\aspnet\EntityFrameworkCore\src\EFCore\Metadata\Builders\ReferenceCollectionBuilder`.cs:line 51
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceCollectionBuilder`2.HasPrincipalKey(String[] keyPropertyNames) in C:\aspnet\EntityFrameworkCore\src\EFCore\Metadata\Builders\ReferenceCollectionBuilder`.cs:line 125
   at Microsoft.EntityFrameworkCore.Query.QueryBugsTest.BloggingContext.<>c.<OnModelCreating>b__1_0(EntityTypeBuilder`1 m) in C:\aspnet\EntityFrameworkCore\test\EFCore.SqlServer.FunctionalTests\Query\QueryBugsTest.cs:line 4992
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity[TEntity](Action`1 buildAction) in C:\aspnet\EntityFrameworkCore\src\EFCore\ModelBuilder.cs:line 134
   at Microsoft.EntityFrameworkCore.Query.QueryBugsTest.BloggingContext.OnModelCreating(ModelBuilder modelBuilder) in C:\aspnet\EntityFrameworkCore\test\EFCore.SqlServer.FunctionalTests\Query\QueryBugsTest.cs:line 4987
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context) in C:\aspnet\EntityFrameworkCore\src\EFCore\Infrastructure\ModelCustomizer.cs:line 52
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context) in C:\aspnet\EntityFrameworkCore\src\EFCore.Relational\Infrastructure\RelationalModelCustomizer.cs:line 61
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator) in C:\aspnet\EntityFrameworkCore\src\EFCore\Infrastructure\ModelSource.cs:line 84
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1() in C:\aspnet\EntityFrameworkCore\src\EFCore\Infrastructure\ModelSource.cs:line 60
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator) in C:\aspnet\EntityFrameworkCore\src\EFCore\Infrastructure\ModelSource.cs:line 56
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel() in C:\aspnet\EntityFrameworkCore\src\EFCore\Internal\DbContextServices.cs:line 71
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model() in C:\aspnet\EntityFrameworkCore\src\EFCore\Internal\DbContextServices.cs:line 93
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_2(IServiceProvider p) in C:\aspnet\EntityFrameworkCore\src\EFCore\Infrastructure\EntityFrameworkServicesBuilder.cs:line 269
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(IServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies() in C:\aspnet\EntityFrameworkCore\src\EFCore\DbContext.cs:line 330
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider() in C:\aspnet\EntityFrameworkCore\src\EFCore\DbContext.cs:line 312
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance() in C:\aspnet\EntityFrameworkCore\src\EFCore\DbContext.cs:line 1466
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance() in C:\aspnet\EntityFrameworkCore\src\EFCore\Infrastructure\DatabaseFacade.cs:line 249
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor) in C:\aspnet\EntityFrameworkCore\src\EFCore\Internal\InternalAccessorExtensions.cs:line 28
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor) in C:\aspnet\EntityFrameworkCore\src\EFCore\Infrastructure\AccessorExtensions.cs:line 46
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_DatabaseCreator() in C:\aspnet\EntityFrameworkCore\src\EFCore\Infrastructure\DatabaseFacade.cs:line 255
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureDeleted() in C:\aspnet\EntityFrameworkCore\src\EFCore\Infrastructure\DatabaseFacade.cs:line 90
   at Microsoft.EntityFrameworkCore.Query.QueryBugsTest.Main() in C:\aspnet\EntityFrameworkCore\test\EFCore.SqlServer.FunctionalTests\Query\QueryBugsTest.cs:line 5010
```
