### ISSUE TITLE
Query: Compiler error when calling Contains on a collection nav

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFrameworkCore#7687]
```c#
 var orders = context.Orders.Where(o => context.Customers.Any(c => c.Orders.Contains(o))).ToList();    
```
```
System.ArgumentException : Expression of type 'Microsoft.EntityFrameworkCore.Specification.Tests.TestModels.Northwind.Order' cannot be used for parameter of type 'Microsoft.EntityFrameworkCore.Storage.ValueBuffer' of method 'Boolean Contains[ValueBuffer](System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Storage.ValueBuffer], Microsoft.EntityFrameworkCore.Storage.ValueBuffer)'
	at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
	at System.Linq.Expressions.Expression.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments)
	at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
	at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression[] arguments)
	E:\dev\github\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\ResultOperatorHandler.cs(375,0): at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.CallWithPossibleCancellationToken(MethodInfo methodInfo, Expression[] arguments)
	E:\dev\github\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\ResultOperatorHandler.cs(155,0): at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.HandleContains(EntityQueryModelVisitor entityQueryModelVisitor, ContainsResultOperator containsResultOperator, QueryModel queryModel)
	E:\dev\github\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\ResultOperatorHandler.cs(35,0): at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.<>c.<.cctor>b__30_6(EntityQueryModelVisitor v, ResultOperatorBase r, QueryModel q)
	E:\dev\github\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\ResultOperatorHandler.cs(78,0): at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
	E:\dev\github\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Query\Internal\RelationalResultOperatorHandler.cs(66,0): at Microsoft.EntityFrameworkCore.Query.Internal.RelationalResultOperatorHandler.HandlerContext.EvalOnClient(Boolean requiresClientResultOperator)
	E:\dev\github\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Query\Internal\RelationalResultOperatorHandler.cs(367,0): at Microsoft.EntityFrameworkCore.Query.Internal.RelationalResultOperatorHandler.HandleContains(HandlerContext handlerContext)
	E:\dev\github\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Query\Internal\RelationalResultOperatorHandler.cs(175,0): at Microsoft.EntityFrameworkCore.Query.Internal.RelationalResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
	E:\dev\github\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\EntityQueryModelVisitor.cs(1112,0): at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
	E:\dev\github\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Query\RelationalQueryModelVisitor.cs(1313,0): at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
	at Remotion.Linq.QueryModelVisitorBase.VisitResultOperators(ObservableCollection`1 resultOperators, QueryModel queryModel)
	at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
	E:\dev\github\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\EntityQueryModelVisitor.cs(756,0): at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
	E:\dev\github\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Query\RelationalQueryModelVisitor.cs(382,0): at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
	E:\dev\github\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore.SqlServer\Query\Internal\SqlServerQueryModelVisitor.cs(92,0): at Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
	E:\dev\github\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Query\RelationalQueryModelVisitor.cs(400,0): at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSubQueryModel(QueryModel queryModel)
	E:\dev\github\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Query\ExpressionVisitors\SqlTranslatingExpressionVisitor.cs(907,0): at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
```

**Comment by anpete** [comment]
Ideally this should translate to an EXISTS via the FK on relational.

**Comment by KhalilMohammad** [comment]
What is the current status of this bug? Is this bug fixed in 2.0

**Comment by maumar** [comment]
The bug is not fixed currently. It's assigned to Backlog milestone which means we are not currently planning to fix it for version 2.1.0 either

**Comment by cblomart** [comment]
Any workaround?

**Comment by cblomart** [comment]
Googled a bit and found this  example 
 var chatsList =_context.Chats.Where(chat => chat.Users.Any(u => u.id== user.id)).ToList();

**Comment by maumar** [comment]
This issue is actually fixed in current bits, as a side effect of some other bug fix.

**Comment by maumar** [comment]
regression test added in f66b89d0133dfef9baef6005d3f335779918203a
