### ISSUE TITLE
SelectExpression Cache:  Memory leak when using method as Func in select statement

### ISSUE THREAD

**Issue by artsiomLikhachou** [aspnet/EntityFrameworkCore#8223]
Using _method_ as Func<TSource, TResult> in the following select statement:
```c#
dbContext
.DbSet<TSource>
.Where<TSource>(x => ...)
.Select<TSource, TResult>(x => method(x))
.ToListAsync()
```
lead to memory growing and possible memory leak problem. The root issue is selecting and mapping result set to another result set using method as func before calling ToList/ToListAsync https://github.com/artsiomLikhachou/bugs/blob/master/TestEfMemoryAsp/TestEfMemory/src/TestEfMemory/ProductService.cs#L24-L25 . Making 1000 requests lead to memory increasing from 150MB to 550MB 
![testefmemory_memoryusage](https://cloud.githubusercontent.com/assets/10990701/25178972/9cac54a8-2510-11e7-892e-0bfdb0eb577a.png)
so that the memory is not deallocated. Analyzing of memory dump pointed me the idea that Select Func was added to MemoryCache which keeps invoker instance (TestEfMemory.ProductService) as well as all its dependencies (TestEfMemory.TestDbContext):
![testefmemory_memorydump](https://cloud.githubusercontent.com/assets/10990701/25179202/8613e340-2511-11e7-9a43-3ca3ec2adabf.png)
In such a way because of MemoryCache instances of services and db context are not exempted, cached db context becomes growing and it leads to memory leak.

If we call ToList/ToListAsync before select and do objects mapping after - there is no memory leak issue.

Is it a bug? I am very curious because so simple code may lead to such unpredictable memory usage and we've faced to this issue in Production.

### Steps to reproduce
You can find example on https://github.com/artsiomLikhachou/bugs/tree/master/TestEfMemoryAsp/TestEfMemory. There is a "Send" button on home page which run N (from "Number of requests to send" input) ajax requests to the endpoint with memory leak. 

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2015

**Comment by artsiomLikhachou** [comment]
Any news, suggestions or plans, guys?

**Comment by anpete** [comment]
@artsiomLikhachou Looking at this now. You should be able to workaround the issue by making the method static.

**Comment by anpete** [comment]
@artsiomLikhachou This issue should be fixed in 2.0.0-preview1, can you confirm?

**Comment by anpete** [comment]
Closing as we haven't heard back and think this is fixed.

**Comment by ydekova** [comment]
@anpete  This is either not fixed or recurring in 2.1.

> You should be able to workaround the issue by making the method static.

I think this works if the method is static, however, if the method is not static the impact is dramatic. 
So far it seems to be one of the main contributors to the memory problem we have after the upgrade (https://github.com/dotnet/coreclr/issues/18577). I'm not sure yet whether it is the only one. We still have some closure objects related to Ef that are not observed in 1.1. and I'm not sure what causes them.

If this is the expected behavior it should be in the documentation or forbidden altogether.

**Comment by ajcvickers** [comment]
@ydekova Can you please open a new issue with a runnable project/solution or complete code listing that demonstrates the behavior you are seeing so that we can fully investigate.
